import numpy as np
a = np.arange(12).reshape(1,12)
print(a)
print(a.shape)
b = a.reshape((3,4))
c = a.reshape((4,3))
d = a.reshape((2,6))
e = b.ravel()
f = c.ravel()
g = d.ravel()
print(e)
print(e.shape)
print(f)
print(f.shape)
print(g)
print(g.shape)